apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-example-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-example
        version: v1
    spec:
      containers:
      - name: python-example
        image: vngrs/python-example:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_USERNAME
          value: "root"
        - name: MYSQL_PASSWORD
          value: "osman"
        - name: MYSQL_INSTANCE_NAME
          value: "osmandb"
        - name: MYSQL_SERVICE_HOST
          value: "?????"
        - name: MYSQL_SERVICE_PORT
          value: "27017"
