apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-example-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-example
        version: v1
    spec:
      containers:
      - name: python-example
        image: ykbacr.azurecr.io/ext/ykbpoc:${GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: azurestack
