apiVersion: v1
kind: Service
metadata:
  name: python-example-svc
spec:
  type: ClusterIP
  selector:
    app: python-example
    version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
