apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "osman"
        - name: MYSQL_DATABASE
          value: "osmandb"
